AllCops:
  NewCops: enable

# Configuration parameters: IndentationWidth.
# SupportedStyles: outdent, indent
Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

# Cop supports --auto-correct.
# Configuration parameters: Width, IgnoredPatterns.
Layout/IndentationWidth:
  Width: 4

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: separated, grouped
Style/AccessorGrouping:
  EnforcedStyle: separated

# Offense count: 2
Style/Documentation:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle.
# SupportedStyles: always, always_true, never
Style/FrozenStringLiteralComment:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

# Cop supports --auto-correct.
# Configuration parameters: EnforcedStyle, AllowInnerSlashes.
# SupportedStyles: slashes, percent_r, mixed
Style/RegexpLiteral:
  EnforcedStyle: mixed
  AllowInnerSlashes: true
